const DUMMY_DATA = [
  {
    id: 1,
    agency: "신한은행",
    amount: 5000000,
    interestRate: 3.5,
    job: "직장인",
    name: "직장인을 위한 긴급 비상금 대출",
    repayPeriod: 365,
    age: "30",
  },
  {
    id: 2,
    agency: "신한은행",
    amount: 3000000,
    interestRate: 1.5,
    job: "학생",
    name: "대학생을 위한 학자금 대출",
    repayPeriod: 730,
    age: 20,
  },
  {
    id: 3,
    agency: "농협은행",
    amount: 8000000,
    interestRate: 3.5,
    job: "프리랜서",
    name: "자유로운 프리랜서들을 위한 코로나 긴급 지원 대출",
    repayPeriod: 365,
    age: 40,
  },
  {
    id: 4,
    agency: "국가장학재단",
    amount: 5000000,
    interestRate: 1.0,
    job: "학생",
    name: "저소득층 및 취약 계층 지원 대출 사업",
    repayPeriod: 1095,
    age: 10,
  },
  {
    id: 5,
    agency: "토스뱅크",
    amount: 10000000,
    interestRate: 3.2,
    job: "무직",
    name: "취업 준비생 및  미래의 꿈나무를  위한  대출 사업",
    repayPeriod: 730,
    age: 20,
  },
  {
    id: 6,
    agency: "신한은행",
    amount: 7000000,
    interestRate: 1.7,
    job: "직장인",
    name: "직장인을 위한 매직카 대출",
    repayPeriod: 1825,
    age: 30,
  },
  {
    id: 7,
    agency: "국민은행",
    amount: 200000000,
    interestRate: 1.5,
    job: "자영업자",
    name: "사장님의 새희망홀씨 긴급생계자금",
    repayPeriod: 3650,
    age: 40,
  },
  {
    id: 8,
    agency: "한국장학재단",
    amount: 5000000,
    interestRate: 1.3,
    job: "학생",
    name: "농촌 출신 대학생을 위한 학자금 대출",
    repayPeriod: 2920,
    age: 20,
  },
  {
    id: 9,
    agency: "신한은행",
    amount: 500000,
    interestRate: 1.6,
    job: "프리랜서",
    name: "프리랜서 든든 신용대출",
    repayPeriod: 2920,
    age: 30,
  },
  {
    id: 10,
    agency: "카카오뱅크",
    amount: 3000000,
    interestRate: 1.8,
    job: "무직",
    name: "취업 햇살론",
    repayPeriod: 2555,
    age: 20,
  },
  {
    id: 11,
    agency: "농협은행",
    amount: 3000000,
    interestRate: 3.12,
    job: "자영업자",
    name: "개인사업자 대출",
    repayPeriod: 150,
    age: 20,
  },
  {
    id: 12,
    agency: "농협은행",
    amount: 1500000,
    interestRate: 1.78,
    job: "직장인",
    name: "근로자안정금 대출",
    repayPeriod: 73,
    age: 32,
  },
  {
    id: 13,
    agency: "하나은행",
    amount: 4500000,
    interestRate: 3.46,
    job: "학생",
    name: "푸른 등대 학자금 대출",
    repayPeriod: 365,
    age: 20,
  },
  {
    id: 14,
    agency: "신한은행",
    amount: 1200000,
    interestRate: 2.43,
    job: "프리랜서",
    name: "프리랜서를 위한 신용대출",
    repayPeriod: 150,
    age: 30,
  },
  {
    id: 15,
    agency: "우리은행",
    amount: 400000,
    interestRate: 4.5,
    job: "무직",
    name: "과학 인재 취준생을 위한 청년대출",
    repayPeriod: 300,
    age: 20,
  },
];

const CART_URL = "/cart";

export { DUMMY_DATA, CART_URL };
